---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# http://fusioninventory.org/documentation/agent/installation/linux/rhel.html

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ fusioninventory__repo_gpgkey }}"
    state: present

- name: Add EPEL Repository
  yum:
    name: "{{ fusioninventory__repo_package }}"
    state: present
