---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# http://fusioninventory.org/documentation/agent/installation/linux/rhel.html

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ fusioninventory__repo_gpgkey }}"
    state: present

- name: Add EPEL Repository
  yum:
    name: "{{ fusioninventory__repo_package }}"
    state: present

- name: RedHat 8 specifics
  block:

  - name: Load additional repository settings for CentOS or RedHat 8
    include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

  - name: Override repository settings for CentOS <= 8.2
    include_vars: "CentOS-8.2.yml"
    when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_version'] | float <= 8.2

  - name: Enable Additional Repository
    ini_file:
      path: "{{ fusioninventory__additional_repo_file }}"
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      mode: "0644"
    loop: "{{ fusioninventory__additional_repo_params }}"

  when: ansible_facts['distribution_major_version'] | int >= 8
